import type {
  BusinessSettings,
  Category,
  DeliveryZone,
  ModifierGroup,
  Product,
  PromoCode,
  SpecialHours,
  WeeklyHours,
} from "./types";

// ---------------------------------------------------------------------------
// Demo / seed data for Piccolo Pizzeria — a real independent wood-fired
// pizza trailer in the North East. The menu, prices and descriptions below
// are taken directly from Piccolo's own menu boards; photography in
// /public/images/real is from their own trailer and oven. Swap addresses,
// hours and placeholder contact details for the real details, then manage
// everything else from `/admin` once Supabase is connected.
//
// This file is the fallback data source whenever Supabase isn't configured
// (local development, previews, or this build) — see `lib/data/*`.
// ---------------------------------------------------------------------------

export const seedBusinessSettings: BusinessSettings = {
  name: "Piccolo Pizzeria",
  tagline: "Woodfired. Hand stretched. Piccolo.",
  phone: "01642 000 000",
  email: "hello@piccolopizzeria.co.uk",
  addressLine1: "Elm Tree Social Club",
  addressLine2: "Bishopton Road West",
  city: "Stockton-on-Tees",
  postcode: "TS19 0QJ",
  latitude: 54.5665,
  longitude: -1.3572,
  instagramUrl: "https://instagram.com/piccolo_pizzeria25",
  facebookUrl: "https://facebook.com/piccolopizzeria",
  orderingPaused: false,
  orderingPausedMessage: "",
  asapOrdersEnabled: true,
  scheduledOrdersEnabled: true,
  deliveryEnabled: false,
  currentWaitMinutes: 25,
  minPrepMinutes: 20,
  maxAdvanceOrderDays: 5,
  slotIntervalMinutes: 15,
  ordersPerSlot: 6,
  deliveryOrdersPerSlot: 3,
};

const closed = { isOpen: false, openTime: "00:00", closeTime: "00:00" };

export const seedWeeklyHours: WeeklyHours = {
  0: { isOpen: true, openTime: "16:00", closeTime: "20:30" }, // Sunday
  1: closed, // Monday — closed
  2: closed, // Tuesday — closed
  3: { isOpen: true, openTime: "17:00", closeTime: "21:00" }, // Wednesday
  4: { isOpen: true, openTime: "17:00", closeTime: "21:00" }, // Thursday
  5: { isOpen: true, openTime: "17:00", closeTime: "21:30" }, // Friday
  6: { isOpen: true, openTime: "12:00", closeTime: "21:30" }, // Saturday
};

export const seedSpecialHours: SpecialHours[] = [
  {
    id: "sh-boxing-day",
    date: "2026-12-26",
    label: "Boxing Day",
    isOpen: false,
  },
];

export const seedCategories: Category[] = [
  { id: "cat-pizzas", slug: "pizzas", name: "Pizzas", description: "Straight from the trailer oven, made to order", sortOrder: 0 },
  { id: "cat-specials", slug: "specials", name: "Pizza Specials", description: "Rotating specials, while they last", sortOrder: 1 },
  { id: "cat-sandwiches", slug: "pizza-sandwiches", name: "Pizza Sandwiches", description: "Our dough, folded and filled, baked in the wood oven", sortOrder: 2 },
  { id: "cat-dips", slug: "dips", name: "Dips", description: "", sortOrder: 3 },
  { id: "cat-drinks", slug: "drinks", name: "Drinks", description: "", sortOrder: 4 },
];

export const seedModifierGroups: ModifierGroup[] = [
  {
    id: "mg-base",
    name: "Choose Your Base",
    required: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      { id: "mo-base-classic", name: "Classic Woodfired Base", priceMinor: 0, isDefault: true },
      { id: "mo-base-gf", name: "Gluten Free Base", priceMinor: 250 },
    ],
  },
  {
    id: "mg-extras",
    name: "Extra Toppings",
    description: "Fired fresh with your pizza",
    required: false,
    minSelect: 0,
    maxSelect: 6,
    options: [
      { id: "mo-ex-mozzarella", name: "Extra Fior di Latte Mozzarella", priceMinor: 150 },
      { id: "mo-ex-honey", name: "Hot Honey Drizzle", priceMinor: 100 },
      { id: "mo-ex-jalapeno", name: "Jalapeños", priceMinor: 100 },
      { id: "mo-ex-crispy-onion", name: "Crispy Onions", priceMinor: 100 },
      { id: "mo-ex-pickled-onion", name: "Pickled Red Onion", priceMinor: 100 },
      { id: "mo-ex-chorizo", name: "Extra Chorizo", priceMinor: 200 },
    ],
  },
  {
    id: "mg-remove",
    name: "Make It Yours",
    description: "Any allergies or intolerances, please contact us before ordering",
    required: false,
    minSelect: 0,
    maxSelect: 3,
    options: [
      { id: "mo-rm-onion", name: "No Red Onion", priceMinor: 0 },
      { id: "mo-rm-sauce", name: "No Tomato Sauce", priceMinor: 0 },
      { id: "mo-rm-cheese", name: "Go Easy on the Cheese", priceMinor: 0 },
    ],
  },
  {
    id: "mg-dip",
    name: "Choose Your Dip",
    required: false,
    minSelect: 0,
    maxSelect: 2,
    options: [
      { id: "mo-dip-garlic-mayo", name: "Garlic Mayo", priceMinor: 100 },
      { id: "mo-dip-franks", name: "Frank's RedHot Sauce", priceMinor: 100 },
    ],
  },
  {
    id: "mg-breakfast-extras",
    name: "Optional Extras",
    required: false,
    minSelect: 0,
    maxSelect: 2,
    options: [
      { id: "mo-bf-black-pudding", name: "Black Pudding", priceMinor: 100 },
      { id: "mo-bf-hash-brown", name: "Hash Browns", priceMinor: 100 },
    ],
  },
];

const PIZZA_MODS = ["mg-base", "mg-extras", "mg-remove"];

export const seedProducts: Product[] = [
  // ---- Pizzas (real Piccolo menu) ----
  {
    id: "p-margherita",
    categoryId: "cat-pizzas",
    slug: "margherita",
    name: "Margherita",
    description: "A classic, with fresh basil, parmesan & fior di latte mozzarella.",
    priceMinor: 1000,
    imageUrl: "placeholder:pizzas:0",
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy"],
    soldOut: false,
    featured: false,
    popular: true,
    isNew: false,
    sortOrder: 0,
    modifierGroupIds: PIZZA_MODS,
  },
  {
    id: "p-pepperoni",
    categoryId: "cat-pizzas",
    slug: "pepperoni",
    name: "Pepperoni",
    description: "Everyone's favourite! Finished with our homemade hot honey.",
    priceMinor: 1100,
    imageUrl: "placeholder:pizzas:1",
    dietary: [],
    allergens: ["gluten", "dairy"],
    soldOut: false,
    featured: false,
    popular: true,
    isNew: false,
    sortOrder: 1,
    modifierGroupIds: PIZZA_MODS,
  },
  {
    id: "p-meat-feast",
    categoryId: "cat-pizzas",
    slug: "meat-feast",
    name: "Meat Feast",
    description: "Salami, ham, pepperoni & chorizo.",
    priceMinor: 1200,
    imageUrl: "placeholder:pizzas:2",
    dietary: [],
    allergens: ["gluten", "dairy"],
    soldOut: false,
    featured: false,
    popular: false,
    isNew: false,
    sortOrder: 2,
    modifierGroupIds: PIZZA_MODS,
  },
  {
    id: "p-hawaiian",
    categoryId: "cat-pizzas",
    slug: "hawaiian",
    name: "Hawaiian",
    description: "Love it or hate it? Ham & pineapple.",
    priceMinor: 1100,
    imageUrl: "placeholder:pizzas:0",
    dietary: [],
    allergens: ["gluten", "dairy"],
    soldOut: false,
    featured: false,
    popular: false,
    isNew: false,
    sortOrder: 3,
    modifierGroupIds: PIZZA_MODS,
  },
  {
    id: "p-vegetarian",
    categoryId: "cat-pizzas",
    slug: "vegetarian",
    name: "Vegetarian",
    description: "Pepper, mushroom, red onion & tomato.",
    priceMinor: 1000,
    imageUrl: "/images/real/pizza-vegetarian.jpg",
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy"],
    soldOut: false,
    featured: false,
    popular: false,
    isNew: false,
    sortOrder: 4,
    modifierGroupIds: PIZZA_MODS,
  },
  {
    id: "p-pesto",
    categoryId: "cat-pizzas",
    slug: "pesto",
    name: "Pesto",
    description: "Red onion, tomato, finished with pesto.",
    priceMinor: 1100,
    imageUrl: "placeholder:pizzas:1",
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy", "nuts"],
    soldOut: false,
    featured: false,
    popular: false,
    isNew: false,
    sortOrder: 5,
    modifierGroupIds: PIZZA_MODS,
  },
  {
    id: "p-chicken-tikka",
    categoryId: "cat-pizzas",
    slug: "chicken-tikka",
    name: "Chicken Tikka",
    description: "Charred pieces of chicken tikka, red onion & jalapeños, drizzled with our house special sauce.",
    priceMinor: 1200,
    imageUrl: "placeholder:pizzas:2",
    dietary: ["spicy"],
    allergens: ["gluten", "dairy"],
    soldOut: false,
    featured: false,
    popular: true,
    isNew: false,
    sortOrder: 6,
    modifierGroupIds: PIZZA_MODS,
  },
  {
    id: "p-bbq-pulled-pork",
    categoryId: "cat-pizzas",
    slug: "bbq-pulled-pork",
    name: "BBQ Pulled Pork",
    description: "Red onion, BBQ pulled pork & a drizzle of BBQ sauce.",
    priceMinor: 1200,
    imageUrl: "placeholder:pizzas:0",
    dietary: [],
    allergens: ["gluten", "dairy"],
    soldOut: false,
    featured: false,
    popular: false,
    isNew: false,
    sortOrder: 7,
    modifierGroupIds: PIZZA_MODS,
  },

  // ---- Specials ----
  {
    id: "p-special-buffalo-chicken",
    categoryId: "cat-specials",
    slug: "buffalo-chicken-feta",
    name: "Buffalo Chicken & Feta",
    description: "Buffalo chicken, feta, finished with spring onion & house made ranch.",
    priceMinor: 1200,
    imageUrl: "placeholder:specials:0",
    dietary: ["spicy"],
    allergens: ["gluten", "dairy"],
    soldOut: false,
    featured: true,
    popular: false,
    isNew: true,
    sortOrder: 0,
    modifierGroupIds: PIZZA_MODS,
  },
  {
    id: "p-special-weekly",
    categoryId: "cat-specials",
    slug: "this-weeks-special",
    name: "This Week's Special",
    description: "A rotating special straight from the wood oven. Ask us what's on today.",
    priceMinor: 1200,
    imageUrl: "/images/real/pizza-special-1.jpg",
    dietary: [],
    allergens: ["gluten", "dairy"],
    soldOut: false,
    featured: true,
    popular: false,
    isNew: false,
    sortOrder: 1,
    modifierGroupIds: ["mg-remove"],
  },

  // ---- Pizza Sandwiches (real Piccolo menu) ----
  {
    id: "p-sandwich-pulled-pork",
    categoryId: "cat-sandwiches",
    slug: "pulled-pork-sandwich",
    name: "Pulled Pork",
    description: "BBQ pulled pork with homemade apple coleslaw, pickled red onion & finished with crispy onions.",
    priceMinor: 1000,
    imageUrl: "placeholder:sides:0",
    dietary: [],
    allergens: ["gluten", "dairy"],
    soldOut: false,
    featured: false,
    popular: true,
    isNew: false,
    sortOrder: 0,
    modifierGroupIds: [],
  },
  {
    id: "p-sandwich-chicken-tikka",
    categoryId: "cat-sandwiches",
    slug: "chicken-tikka-sandwich",
    name: "Chicken Tikka",
    description: "Charred chunks of chicken tikka served with Indian style salad, house special sauce & crispy onions.",
    priceMinor: 1000,
    imageUrl: "placeholder:sides:1",
    dietary: ["spicy"],
    allergens: ["gluten", "dairy"],
    soldOut: false,
    featured: false,
    popular: false,
    isNew: false,
    sortOrder: 1,
    modifierGroupIds: [],
  },
  {
    id: "p-sandwich-mortadella-burrata",
    categoryId: "cat-sandwiches",
    slug: "mortadella-burrata-sandwich",
    name: "Mortadella & Burrata",
    description: "Italian ham served with fresh burrata, pesto and topped with crushed pistachios.",
    priceMinor: 1000,
    imageUrl: "placeholder:sides:0",
    dietary: [],
    allergens: ["gluten", "dairy", "nuts"],
    soldOut: false,
    featured: true,
    popular: false,
    isNew: false,
    sortOrder: 2,
    modifierGroupIds: [],
  },
  {
    id: "p-sandwich-caprese",
    categoryId: "cat-sandwiches",
    slug: "caprese-sandwich",
    name: "Caprese",
    description: "Fresh mozzarella, cherry tomatoes, fresh basil & pesto.",
    priceMinor: 800,
    imageUrl: "placeholder:sides:1",
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy", "nuts"],
    soldOut: false,
    featured: false,
    popular: false,
    isNew: false,
    sortOrder: 3,
    modifierGroupIds: [],
  },
  {
    id: "p-sandwich-breakfast",
    categoryId: "cat-sandwiches",
    slug: "breakfast-sandwich",
    name: "Breakfast Sandwich",
    description: "Bacon, sausage & fried egg.",
    priceMinor: 800,
    imageUrl: "placeholder:sides:0",
    dietary: [],
    allergens: ["gluten", "dairy", "eggs"],
    soldOut: false,
    featured: false,
    popular: false,
    isNew: false,
    sortOrder: 4,
    modifierGroupIds: ["mg-breakfast-extras"],
  },

  // ---- Dips ----
  {
    id: "p-dip-garlic-mayo",
    categoryId: "cat-dips",
    slug: "garlic-mayo",
    name: "Garlic Mayo",
    description: "",
    priceMinor: 100,
    imageUrl: "placeholder:dips:0",
    dietary: ["vegetarian"],
    allergens: ["eggs"],
    soldOut: false,
    featured: false,
    popular: false,
    isNew: false,
    sortOrder: 0,
    modifierGroupIds: [],
  },
  {
    id: "p-dip-franks",
    categoryId: "cat-dips",
    slug: "franks-redhot",
    name: "Frank's RedHot Sauce",
    description: "",
    priceMinor: 100,
    imageUrl: "placeholder:dips:0",
    dietary: ["vegan", "spicy"],
    allergens: [],
    soldOut: false,
    featured: false,
    popular: false,
    isNew: false,
    sortOrder: 1,
    modifierGroupIds: [],
  },

  // ---- Drinks ----
  {
    id: "p-coke",
    categoryId: "cat-drinks",
    slug: "coca-cola",
    name: "Coca-Cola",
    description: "330ml can",
    priceMinor: 150,
    imageUrl: "placeholder:drinks:0",
    dietary: ["vegan"],
    allergens: [],
    soldOut: false,
    featured: false,
    popular: false,
    isNew: false,
    sortOrder: 0,
    modifierGroupIds: [],
  },
  {
    id: "p-diet-coke",
    categoryId: "cat-drinks",
    slug: "diet-coke",
    name: "Diet Coke",
    description: "330ml can",
    priceMinor: 150,
    imageUrl: "placeholder:drinks:1",
    dietary: ["vegan"],
    allergens: [],
    soldOut: false,
    featured: false,
    popular: false,
    isNew: false,
    sortOrder: 1,
    modifierGroupIds: [],
  },
  {
    id: "p-water",
    categoryId: "cat-drinks",
    slug: "still-water",
    name: "Still Water",
    description: "500ml",
    priceMinor: 120,
    imageUrl: "placeholder:drinks:0",
    dietary: ["vegan"],
    allergens: [],
    soldOut: false,
    featured: false,
    popular: false,
    isNew: false,
    sortOrder: 2,
    modifierGroupIds: [],
  },
];

export const seedDeliveryZones: DeliveryZone[] = [
  { id: "dz-ts18", postcodePrefixes: ["TS18"], feeMinor: 250, minOrderMinor: 1500, freeDeliveryThresholdMinor: 3500, estimatedMinutes: 35 },
  { id: "dz-ts17-19", postcodePrefixes: ["TS17", "TS19"], feeMinor: 350, minOrderMinor: 1800, freeDeliveryThresholdMinor: 4000, estimatedMinutes: 40 },
];

export const seedPromoCodes: PromoCode[] = [
  {
    id: "promo-welcome10",
    code: "WELCOME10",
    type: "percentage",
    value: 10,
    minBasketMinor: 1500,
    usageLimit: undefined,
    timesUsed: 0,
    active: true,
  },
  {
    id: "promo-piccolo5",
    code: "PICCOLO5",
    type: "fixed",
    value: 500,
    minBasketMinor: 2500,
    usageLimit: undefined,
    timesUsed: 0,
    active: true,
  },
];
